### ISSUE TITLE
Lock screen wallpaper

### ISSUE THREAD

**Issue by enrique95** [ManApart/palette-cycle#1]
Is there a way to establish your homescreen wallpaper as your lock screen wallpaper too?  As far as I'm aware the app only lets you set the homescreen but the lock screen would look fantastic too with it

**Comment by ManApart** [comment]
Hey Enrique,

You should be able to set the lock screen when you say 'set wallpaper'. If not, it may be because you're on an earlier version of android? It might be worth googling that question in general.

![image](https://user-images.githubusercontent.com/4498895/152684506-6feef885-407b-4098-b9a9-a3d861656600.png)

I'm going to close this for now as this has worked for me.

**Comment by enrique95** [comment]
Hello! Now that I'm using a new phone I see that in Android 11 it does give you the both options. I didn't know if that was an specific thing from the app or just Android 8 in general. Thank you for your answer!
